[package]
name = "ethp2p-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anvil-core = { git = "https://github.com/foundry-rs/foundry" }
foundry-config = { git = "https://github.com/foundry-rs/foundry" }
ethers = { git = "https://github.com/gakonst/ethers-rs" }
bytes = { version = "1.1.0" }
serde = "1.0.137"
serde_json = "1.0.81"
fastrlp = { version = "0.1.0", features = ["alloc", "derive", "std"] }
ruint = { git = "https://github.com/recmo/uint", features = ["fastrlp", "serde"] }
ethereum-forkid = { git = "https://github.com/rust-ethereum/forkid" }

[dev-dependencies]
hex-literal = "0.3.4"
hex = "0.4.3"

[patch.crates-io]
fastrlp = { git = "https://github.com/rjected/fastrlp", branch = "implement-ethereum-types", features = ["std", "derive", "ethereum-types"] }

[patch."https://github.com/foundry-rs/foundry"]
anvil-core = { git = "https://github.com/rjected/foundry", branch = "fastrlp" }
foundry-config = { git = "https://github.com/rjected/foundry", branch = "fastrlp" }

[patch."https://github.com/gakonst/ethers-rs"]
ethers = { git = "https://github.com/rjected/ethers-rs", branch = "fastrlp" }
ethers-core = { git = "https://github.com/rjected/ethers-rs", branch = "fastrlp" }
ethers-signers = { git = "https://github.com/rjected/ethers-rs", branch = "fastrlp" }
ethers-etherscan = { git = "https://github.com/rjected/ethers-rs", branch = "fastrlp" }
ethers-providers = { git = "https://github.com/rjected/ethers-rs", branch = "fastrlp" }
ethers-solc = { git = "https://github.com/rjected/ethers-rs", branch = "fastrlp", features = ["async", "svm-solc"] }
ethers-contract = { git = "https://github.com/rjected/ethers-rs", branch = "fastrlp" }
