[package]
name = "ethp2p-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
fastrlp = { version = "0.1.0", features = ["alloc", "derive", "std"] }
ruint = { git = "https://github.com/recmo/uint", features = ["fastrlp"] }
ethereum-forkid = { git = "https://github.com/rust-ethereum/forkid" }
anvil-core = { git = "https://github.com/foundry-rs/foundry" }

[dev-dependencies]
hex-literal = "0.3.4"
